# Generated by Django 4.2.7 on 2023-12-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FruitCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_image', models.ImageField(upload_to='images/')),
                ('fruit_likes', models.IntegerField(default=0)),
                ('fruit_name', models.CharField(max_length=50)),
                ('fruits_about', models.CharField(max_length=500)),
                ('on_sale', models.BooleanField(default=False)),
                ('fruits_price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainn_page.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=50)),
                ('text', models.TextField(max_length=800)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('fruit_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits_comments', to='mainn_page.fruitcarts')),
            ],
        ),
    ]
