# Generated by Django 4.2.7 on 2023-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitcarts',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
    ]
