# Generated by Django 4.2.7 on 2023-12-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageglobalveraibles',
            name='image',
            field=models.ImageField(editable='True', upload_to='images/'),
        ),
    ]
